### ISSUE TITLE
Error in set spacing

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/mdreg#28]
SetSpacing throws this error with spacing set to 1.0

```
Traceback (most recent call last):
  File "c:\Users\steve\Dropbox\Software\QIB-Sheffield\TRISTAN-human\main.py", line 24, in <module>
    mdr.fit()
  File "c:\Users\steve\Dropbox\Software\QIB-Sheffield\TRISTAN-human\mdreg\main.py", line 90, in fit
    deformation = self.fit_deformation()
  File "c:\Users\steve\Dropbox\Software\QIB-Sheffield\TRISTAN-human\mdreg\main.py", line 153, in fit_deformation
    mask_t,
    source.SetSpacing(spacing)
  File "C:\Users\steve\Documents\env\lib\site-packages\SimpleITK\SimpleITK.py", line 3212, in SetSpacing
    return _SimpleITK.Image_SetSpacing(self, spacing)
TypeError: in method 'Image_SetSpacing', argument 2 of type 'std::vector< double,std::allocator< double > > const &'    
```

Here is the code to reproduce the bug (working off TRISTAN human data). After commenting out SetSpacing everything works fine

```python
# Get data
path = 'C:\\Users\\steve\\Dropbox\\Data\\TRISTAN_patient_examples_2\\v4_1\\data-rzp2'
folder = db.Folder(path, attributes=attr)
series = folder.series(SeriesDescription='dev')[0]
array, dataset = series.array(['AcquisitionTime'], pixels_first=True)

# Perform mdreg
mdr = MDReg()
mdr.set_array(np.squeeze(array[...,0]))
mdr.fit()
```

**Comment by KanishkaS** [comment]
added slice thickness to the spacing option (see below 3D example) and this works well. Issue now resolved.

    mdr.pixel_spacing = header[0,0,0].PixelSpacing # 3D volume spacing
    mdr.slice_thickness = header[0,0,0].SliceThickness # 3D volume spacing 
    mdr.pixel_spacing.append(mdr.slice_thickness)
