### ISSUE TITLE
AttributeError: PyCapsule_Import "_ITKCommonPython._C_API" is not valid

### ISSUE THREAD

**Issue by JoaoPeriquito** [QIB-Sheffield/mdreg#38]
**Python version: 3.9.10**

Traceback (most recent call last):
  File "c:\users\md1jdsp\documents\github\wezel\src\wezel\core.py", line 189, in <lambda>
    self.triggered.connect(lambda: self.run(self.app))
  File "c:\Users\md1jdsp\Documents\GitHub\iBEAt\actions\mdr.py", line 112, in run
    _mdr(app, series, number_slices, array, header, signal_model, elastix_file, signal_pars, sort_by='None', study=study)
  File "c:\Users\md1jdsp\Documents\GitHub\iBEAt\actions\mdr.py", line 257, in _mdr
    mdr = mdreg.MDReg()
  File "c:\users\md1jdsp\documents\github\mdreg\src\mdreg\main.py", line 25, in __init__
    self.elastix = default_bspline('2')
  File "c:\users\md1jdsp\documents\github\mdreg\src\mdreg\main.py", line 220, in default_bspline
    param_obj = itk.ParameterObject.New()
  File "C:\Users\md1jdsp\Documents\GitHub\iBEAt\.venv\lib\site-packages\itk\support\lazy.py", line 138, in __getattribute__
    base.itk_load_swig_module(module, namespace)
  File "C:\Users\md1jdsp\Documents\GitHub\iBEAt\.venv\lib\site-packages\itk\support\base.py", line 132, in itk_load_swig_module
    l_module = loader.load(swig_module_name)
  File "C:\Users\md1jdsp\Documents\GitHub\iBEAt\.venv\lib\site-packages\itk\support\base.py", line 291, in load
    l_spec.loader.exec_module(l_module)  # pytype: disable=attribute-error
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\md1jdsp\Documents\GitHub\iBEAt\.venv\lib\site-packages\itk\support\..\ElastixPython.py", line 13, in <module>
    from . import _ElastixPython
**AttributeError: PyCapsule_Import "_ITKCommonPython._C_API" is not valid**

**Comment by KanishkaS** [comment]
This is a recent issue with itk-elastix library. I cannot reproduce this error but will look into this. 

https://github.com/InsightSoftwareConsortium/ITK/pull/3494#issuecomment-1193426410

**Comment by KanishkaS** [comment]
Issue present in the following itk installation version:

itk              5.3rc4.post1
itk-core         5.3rc4.post1
itk-elastix      0.14.1
itk-filtering    5.3rc4.post2
itk-io           5.3rc4.post2
itk-numerics     5.3rc4.post2
itk-registration 5.3rc4.post2
itk-segmentation 5.3rc4.post2

Works for:
itk              5.3rc4.post1
itk-core         5.3rc4.post1
itk-elastix      0.14.1
itk-filtering    5.3rc4.post1
itk-io           5.3rc4.post1
itk-numerics     5.3rc4.post1
itk-registration 5.3rc4.post1
itk-segmentation 5.3rc4.post1

**Comment by JoaoPeriquito** [comment]
Uninstall all "post2" itk packages
install version: itk version 5.3rc4 using the command "pip install itk==5.3rc4"
install version itk-elastix version 0.12.0 using the command "pip install itk-elastix==0.12.0"
